-- TARİH GÖRE SİPARİŞ DAĞILIMINI GETİREN SQL İFADESİ
SELECT 
	DATEPART (YEAR, O.DATE_) AS [YIL],
	CASE 
		WHEN DATEPART (MONTH, O.DATE_) = 1 THEN 'OCAK'
		WHEN DATEPART (MONTH, O.DATE_) = 2 THEN 'ŞUBAT'
		WHEN DATEPART (MONTH, O.DATE_) = 3 THEN 'MART'
		WHEN DATEPART (MONTH, O.DATE_) = 4 THEN 'NİSAN'
		WHEN DATEPART (MONTH, O.DATE_) = 5 THEN 'MAYIS'
		WHEN DATEPART (MONTH, O.DATE_) = 6 THEN 'HAZIRAN'
		WHEN DATEPART (MONTH, O.DATE_) = 7 THEN 'TEMMUZ'
		WHEN DATEPART (MONTH, O.DATE_) = 8 THEN 'AĞUSTOS'
		WHEN DATEPART (MONTH, O.DATE_) = 9 THEN 'EYLÜL'
		WHEN DATEPART (MONTH, O.DATE_) = 10 THEN 'EKİM'
		WHEN DATEPART (MONTH, O.DATE_) = 11 THEN 'KASIM'
		WHEN DATEPART (MONTH, O.DATE_) = 12 THEN 'ARALIK'
	END [AY],
	SUM(OD.LINETOTAL) AS [TOPLAM SIPARIS TUTARI],
	SUM(OD.AMOUNT) AS [TOPLAM SIPARIS ADEDI],
	COUNT(OD.ID) AS [TOPLAM SIPARIS SAYISI]
FROM ORDERS O 
	INNER JOIN ADDRESS A ON A.USERID = O.ADDRESSID
	INNER JOIN CITIES CT ON CT.ID = A.CITYID
	INNER JOIN TOWNS T ON T.ID = A.TOWNID
	INNER JOIN DISTRICTS D ON D.ID = A.DISTRICTID
	INNER JOIN USERS U ON  U.ID = O.USERID
	INNER JOIN PAYMENTS P ON P.ORDERID = O.ID
	INNER JOIN INVOICES I ON I.ORDERID = O.ID
	INNER JOIN ORDERDETAILS OD ON OD.ORDERID = O.ID
	INNER JOIN ITEMS ITM ON ITM.ID = OD.ITEMID 
GROUP BY  DATEPART (YEAR, O.DATE_), DATEPART (MONTH, O.DATE_)
ORDER BY  DATEPART (YEAR, O.DATE_), DATEPART (MONTH, O.DATE_)