-- ORTALAMA TESLİMAT SÜRESİ
SELECT 
	CT.CITY,
	MIN(DATEDIFF (HOUR, O.DATE_, I.DATE_)) AS [EN KISA TESLIMAT SURESI],
	AVG(DATEDIFF (HOUR, O.DATE_, I.DATE_)) AS [ORTALAMA TESLIMAT SURESI],
	MAX(DATEDIFF (HOUR, O.DATE_, I.DATE_)) AS [EN UZUN TESLIMAT SURESI],
	SUM(O.TOTALPRICE) AS [TOPLAM SIPARIS TUTARI],
	COUNT(O.ID) AS [TOPLAM SIPARIS SAYISI]
FROM ORDERS O 
	INNER JOIN ADDRESS A ON A.USERID = O.ADDRESSID
	INNER JOIN CITIES CT ON CT.ID = A.CITYID
	INNER JOIN TOWNS T ON T.ID = A.TOWNID
	INNER JOIN DISTRICTS D ON D.ID = A.DISTRICTID
	INNER JOIN USERS U ON  U.ID = O.USERID
	INNER JOIN PAYMENTS P ON P.ORDERID = O.ID
	INNER JOIN INVOICES I ON I.ORDERID = O.ID
GROUP BY CT.CITY
ORDER BY CT.CITY
