-- ÖDEME TÜRÜNE GÜRE YIL VE AYLARA GÖRE ÖDEME DAĞILIMIINI GÖSTEREN RUPLANDIRAN SQL İFADESİ
SELECT 
	DATEPART (YEAR, DATE_) AS [YIL],
	DATEPART (MONTH, DATE_) AS [AY],
	CASE 
		WHEN PAYMENTTYPE = 1 THEN 'KREDİ KARTI'
		WHEN PAYMENTTYPE = 2 THEN 'BANKA HAVALESİ'
	END [ODEME TURLLERI],
	SUM(PAYMENTTOTAL) AS [TOPLAM ODEME]
FROM PAYMENTS
GROUP BY DATEPART (YEAR, DATE_), DATEPART (MONTH, DATE_), PAYMENTTYPE
ORDER BY DATEPART (YEAR, DATE_), DATEPART (MONTH, DATE_)