-- ETRADE Veritabanından
-- [Kullanıcı AdI], [Ad Soyad], [İl], [İlçe], [Semt], [Açık adres], [Sipariş ID],
-- [Tarih], [Toplam Tutar], [Ödeme Tarihi], [Banka Onay kodu], [Fatura Tarihi] ve [Kargo Fiş No]
-- getirilecek olan alanlardır. 

SELECT 
    U.USERNAME_ AS [KULLANICI ADI],
    U.NAMESURNAME AS [AD SOYAD], 
    CT.CITY AS [IL], 
    T.TOWN AS [ILCE],
    D.DISTRICT AS [SEMT],
    A.ADDRESSTEXT AS [ADRES],
    O.ID AS [SIPARIS NO],
    O.DATE_ AS [TARIH],
    O.TOTALPRICE AS [TOPLAM TUTAR],
    P.DATE_ AS [ODEME TARIHI],
    P.APPROVECODE AS [BANKA ONAY KODU],
    I.DATE_ AS [FATURA TARIHI],
    I.CARGOFICHENO AS [KARGO FIS NO]
FROM ORDERS O 
    INNER JOIN ADDRESS A ON A.USERID = O.ADDRESSID
    INNER JOIN CITIES CT ON CT.ID = A.CITYID
    INNER JOIN TOWNS T ON T.ID = A.TOWNID
    INNER JOIN DISTRICTS D ON D.ID = A.DISTRICTID
    INNER JOIN USERS U ON  U.ID = O.USERID
    INNER JOIN PAYMENTS P ON P.ORDERID = O.ID
    INNER JOIN INVOICES I ON I.ORDERID = O.ID
WHERE U.NAMESURNAME = 'Berna EDALI'



