---------------------- TSQL değişken tanımlama

-- İki sayıyı toplan TSQL kodları 

DECLARE @SAYI1 AS INTEGER;
SET @SAYI1 = 10;
DECLARE @SAYI2 AS INTEGER;
SET @SAYI2 = 20;
DECLARE @TOPLAM AS INTEGER;
SET @TOPLAM = @SAYI1 + @SAYI2;

SELECT @SAYI1 AS SAYI_1, @SAYI2 AS SAYI_2, @TOPLAM AS TOPLAM;

-- Günün tarihini değişkene almak
DECLARE @TARIH AS DATETIME;
SET @TARIH = GETDATE();
SELECT @TARIH;

-------------------------- TSQL String Fonksiyonları

-- SUBSTRING() 
DECLARE @KELIME AS VARCHAR(100);
SET @KELIME = 'MERHABA DÜNYA';
SELECT SUBSTRING(@KELIME, 1,7);  -- Geri dönüş değeri MERHABA

-- LOWER(), UPPER()
DECLARE @KELIME AS VARCHAR(100);
SET @KELIME = 'Merhaba Dünya';
SELECT LOWER(@KELIME); -- Sonuç : merhaba dünya
SELECT UPPER(@KELIME); -- Sonuç : MERHABA DÜNYA

-- STRİNG BİRLEŞTİRME
DECLARE @AD AS VARCHAR(100) = 'ABDULLAH';
DECLARE @SOYAD AS VARCHAR(100) = 'ŞENTÜRK';
SELECT @AD + ' ' + @SOYAD

-- LEFT(), RIGHT()
DECLARE @KELIME AS VARCHAR(100);
SET @KELIME = 'Merhaba Dünya';
SELECT LEFT(@KELIME, 7), RIGHT(@KELIME, 5);

-- LTRIM(), RTRIM(), TRIM()
DECLARE @KELIME AS VARCHAR(100);
SET @KELIME = '      Merhaba Dünya        ';
SELECT LTRIM(@KELIME), RTRIM(@KELIME), TRIM(@KELIME), LTRIM(RTRIM(@KELIME))

-- REPLACE() Fonksiyonu 
DECLARE @KELIME AS VARCHAR(100);
SET @KELIME = 'Merhaba Dünya';
SELECT REPLACE(@KELIME, 'Merhaba', 'HELLO');

-- LEN() Fonksiyonu  
DECLARE @KELIME AS VARCHAR(100);
SET @KELIME = 'Merhaba Dünya';
SELECT LEN(@KELIME)

-- STRING_SPLIT() Fonksiyonu
DECLARE @KELIME AS VARCHAR(100);
SET @KELIME = 'Merhaba Dünya';
SELECT * FROM string_split(@KELIME, ' ');


---------------------------DATETIME FONKSİYONLARI 

-- DATEADD() Fonksiyonu
DECLARE @TARIH1 AS DATETIME;
SET @TARIH1 = '2019-01-01 16:21:37';
DECLARE @TARIH2 AS DATETIME;
SET @TARIH2 = DATEADD(MONTH, 6, @TARIH1);
SELECT @TARIH1, @TARIH2;

-- DATEDIFF() Fonksiyonu
DECLARE @TARIH1 AS DATETIME;
SET @TARIH1 = '2019-01-01 16:21:37';
DECLARE @TARIH2 AS DATETIME;
SET @TARIH2 = DATEADD(MONTH, 6, @TARIH1);
SELECT @TARIH1, @TARIH2;
SELECT DATEDIFF(MONTH, @TARIH1, @TARIH2);

-- DATEFROMPARTS() 
DECLARE @TARIH1 AS DATETIME;
SET @TARIH1 = DATEFROMPARTS(2022,05,05);
SELECT @TARIH1

-- DATEPART()
DECLARE @TARIH1 AS DATETIME;
SET @TARIH1 = '2019-01-01 16:21:37';
SELECT DATEPART(YEAR, @TARIH1) AS YIL;
SELECT DATEPART(MONTH, @TARIH1) AS AY;
SELECT DATEPART(DAY, @TARIH1) AS GUN;

-- GETDATE()
SELECT GETDATE()

------------- TSQL DÖNGÜLER ----------------------

DECLARE @I AS INT = 0
WHILE @I < 10
BEGIN 
	INSERT INTO TARIHLER (TARIH) VALUES (GETDATE());
	WAITFOR DELAY '00:00:05';
	SET @I = @I + 1;
END

SELECT * FROM TARIHLER

-- ISIMLER, SOYISIMLER TABLOSUNDAN BULUNAN BİLGİLERDEN  
-- KİŞİLER TABLOSUNA RASTGELE AD, SOYAD, DOĞUM TARİHİ, YAŞ, YAŞGRUBU BİLGİLERİNİ  
-- KİŞİLER TABLOSUNA  TSQL KOMUTLARI İLE OLUŞTURALIM

DECLARE @AD AS VARCHAR(50);
DECLARE @SOYAD AS VARCHAR(50);
DECLARE @CINSIYET AS VARCHAR(1);
DECLARE @DOGUMTARIHI AS DATE;
DECLARE @YAS AS INT;
DECLARE @YASGRUBU AS VARCHAR(30);

WHILE @I < 1
BEGIN 

	SELECT @AD = AD, @CINSIYET = CINSIYET 
	FROM ISIMLER
	WHERE ID = ROUND(RAND() * 611, 0); -- 611 KAYITTAN RASTGELE AD VE CINSIYET ÇEKER

	SELECT @SOYAD = SOYISIM 
	FROM SOYISIMLER 
	WHERE ID = ROUND(RAND() * 1000, 0); -- 1000 KAYITTAN RASTGELE SOYISIM ÇEKER

	SET @DOGUMTARIHI = DATEADD(DAY, ROUND(RAND() * 18250, 0), '1950-01-01');
	SET @YAS = DATEDIFF(YEAR, @DOGUMTARIHI, GETDATE());

	IF @YAS BETWEEN 10 AND 20 
		SET @YASGRUBU = '20 YAŞ ALTI'
	IF @YAS BETWEEN 21 AND 30 
		SET @YASGRUBU = '20 - 30 YAŞ ARASI'
	IF @YAS BETWEEN 31 AND 40 
		SET @YASGRUBU = '30 - 40 YAŞ ARASI'
	IF @YAS BETWEEN 41 AND 50 
		SET @YASGRUBU = '40 - 50 YAŞ ARASI'
	IF @YAS BETWEEN 51 AND 60 
		SET @YASGRUBU = '50 - 60 YAŞ ARASI'
	IF @YAS > 60 
		SET @YASGRUBU = '60 TAN BÜYÜK YAŞ GRUBU'

	INSERT INTO KISILER (@AD, @SOYAD, @CINSIYET, @DOGUMTARIHI, @YAS, @YASGRUBU)	
	VALUES (@AD, @SOYAD, @CINSIYET, @DOGUMTARIHI, @YAS, @YASGRUBU)

	SET @I = @I + 1;
END

SELECT * FROM KISILER



















